### ISSUE TITLE
Package Error

### ISSUE THREAD

**Issue by syntaxruns** [rivo/uniseg#22]
![error](https://user-images.githubusercontent.com/71311092/181204884-4accab8b-0b2e-46bd-a338-c8fcda44b87c.png)

**Comment by rivo** [comment]
Which Go version are you using? Does this happen with Go 1.18, too?

**Comment by lounerios** [comment]
@rivo i have the same problem with go 1.15

**Comment by rivo** [comment]
Please upgrade to Go 1.18, the current version. This package requires v1.18 for various reasons.
