### ISSUE TITLE
The difference between V0.2.0 and the latest version

### ISSUE THREAD

**Issue by xuetuyic1** [rivo/uniseg#23]
Since my Golang version is 1.12, I can only use version v0.2.0. I want to confirm the difference between V0.2.0 and the latest version

Could someone help me out?

**Comment by rivo** [comment]
In addition to grapheme cluster breaking, `uniseg` now also supports word breaking, sentence breaking and line breaking (=word wrapping). And there are additional tools that come with a big performance improvement over using the `Graphemes` class.

If you don't need any of that, it's fine to keep using the old version.

Also, the new version is backwards-compatible. So even if you upgrade at a later time, you will not have to make any changes to your code.
