### ISSUE TITLE
golang v1.19 support

### ISSUE THREAD

**Issue by bilalcaliskan** [rivo/uniseg#25]
Currently we are having problem while using this library with Golang v1.19 projects. 

`note: module requires Go 1.18
`

Golang 1.19 is now latest stable version. Are you planning to support v1.19 soon?

**Comment by rivo** [comment]
v1.18 is the minimum version. `uniseg` works fine with v1.19. I wonder what actual problems you are having?

**Comment by bilalcaliskan** [comment]
the whole error is like below

```
# github.com/rivo/uniseg
Error: vendor/github.com/rivo/uniseg/properties.go:130:6: missing function body
Error: vendor/github.com/rivo/uniseg/properties.go:130:20: syntax error: unexpected [, expecting (
note: module requires Go 1.18
```

but the funny thing, i am not getting the same error on my local machine, i get that error only Github Actions which is my CI environment

**Comment by rivo** [comment]
This sounds very much like GitHub Actions is running a Go version older than 1.18. It doesn't recognize generics, which were introduced in 1.18.

**Comment by bilalcaliskan** [comment]
thats exactly what you ve said! thanks for your rapid help, i am closing this issue since it is not related with uniseg anymore.
