### ISSUE TITLE
Result difference between uniseg.GraphemeClusterCount and PHP grapheme_strlen

### ISSUE THREAD

**Issue by jiwandono** [rivo/uniseg#30]
Hello!

I observed the following difference with the mentioned sequences. To be honest I'm not sure which one is correct, but could you help to confirm if the result is expected with uniseg library?

Thank you!

--

**Golang with `uniseg.GraphemeClusterCount`**

```golang
package main

import (
	"fmt"

	"github.com/rivo/uniseg" // v0.4.3
)

func main() {
	fmt.Println(uniseg.GraphemeClusterCount("\r\n\uFE0E"))
	fmt.Println(uniseg.GraphemeClusterCount("\n\uFE0E"))
}
```

Output:
```
1
2
```

https://goplay.tools/snippet/WBIJQfKZs7g

**PHP 8.0.28 with `grapheme_strlen`**

```php
<?php
printf("%d\n", grapheme_strlen("\r\n\u{FE0E}"));
printf("%d\n", grapheme_strlen("\n\u{FE0E}"));
```

Output:
```
2
2
```

https://onlinephp.io/c/2cb86

**Comment by adijiwa** [comment]
On python with https://pypi.org/project/grapheme/

```python
>>> grapheme.length('\r\n\U0000FE0E')
2
>>> grapheme.length('\n\U0000FE0E')
2
```

**Comment by jiwandono** [comment]
On python with https://pypi.org/project/grapheme/

```python
>>> grapheme.length('\r\n\U0000FE0E')
2
>>> grapheme.length('\n\U0000FE0E')
2
```

**Comment by rivo** [comment]
Good catch! One of the transitions in the state machine was not correct, which led to the rule [GB9](https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules) to be preferred over GB4. This should be fixed now.

It's interesting that the official Unicode test cases do not include this combination. (It's not a typical string found in the wild but they should still include this one.)
