### ISSUE TITLE
Decode last grapheme cluster

### ISSUE THREAD

**Issue by zyedidia** [rivo/uniseg#43]
Would it be possible to efficiently decode the last grapheme cluster in a string/byte slice? The `First` functions are great, but it would be nice to be able to iterate in reverse as well, just like with runes with `utf8.DecodeLastRune`.

I briefly looked over the Unicode spec, and it said "By constructing a state table for the reverse direction from the same specification of the rules, reverse iteration is possible," which suggests that it is possible, though I don't know if it's easy to implement.

Thanks!

**Comment by rivo** [comment]
The current implementation is a state machine that's built to move forward through text. If the Unicode spec says that you can derive an equivalent state machine from it which will allow you to move backwards, I guess it's possible in theory. Exercise left to the reader. I don't think it's a trivial task to do that correctly. And even if you manage, it will likely lead to a duplication of a lot of the existing code.

I currently don't have plans to add this to the package. You wrote "it would be nice" which makes me wonder if it's something that is really needed (not just by you but also by other people). I wondered about this once myself over at [`tview`](https://github.com/rivo/tview), for example when the user moves the cursor backwards in a  [`TextArea`](https://pkg.go.dev/github.com/rivo/tview#TextArea) element, but even if I had had backwards-parsing of grapheme clusters available, it wouldn't have solved my problem as I also needed all the other features (e.g. word boundaries, line breaking) and it's unclear to me if they can also be reversed. (I don't suppose they can.)

So I typically end up parsing ahead from a prior position, and this works fine in all the cases I've encountered so far.

**Comment by zyedidia** [comment]
Sounds good, thanks for the info.
