### ISSUE TITLE
Building with bazel

### ISSUE THREAD

**Issue by bradcater** [rivo/uniseg#44]
Have you used uniseg in a bazel project? I'm not able to import it due to there not being a BUILD.bazel file.

**Comment by rivo** [comment]
No, `uniseg` is not configured for Bazel. If you need such configuration files, you'll have to add them yourself.

**Comment by bradcater** [comment]
@rivo Ack. Here's a PR: https://github.com/rivo/uniseg/pull/45

**Comment by stevebarrau** [comment]
You could use https://github.com/bazelbuild/bazel-gazelle to pull this in. You will need the following extra configuration for the go_repository:

```
build_directives = [
    "gazelle:exclude gen_properties.go",
    "gazelle:exclude gen_breaktest.go",
],
```
