### ISSUE TITLE
Inconsistencies for some string widths

### ISSUE THREAD

**Issue by mikelorant** [rivo/uniseg#51]
Have been doing some testing with terminal compatibility and seeing how uniseg differs in string width results.

Using WezTerm, I have found the results nearly identical when comparing 4733 emojis. Great result compared to many other terminals. 👍 

However the following table was output from my test app with some differences. I am uncertain where the problems are and am seeking some guidance on the expected outcome.

```
┌12┐ ┌ String Width ────────────────────┐ ┌ Info ─────────────────────┐
│🏻│ │ Library: 0 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [1f3fb]
│🏼│ │ Library: 0 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [1f3fc]
│🏽│ │ Library: 0 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [1f3fd]
│🏾│ │ Library: 0 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [1f3fe]
│🏿│ │ Library: 0 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [1f3ff]
│〰│ │ Library: 1 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [3030]
│〽│ │ Library: 1 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [303d]
│*️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [2a fe0f 20e3]
│0️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [30 fe0f 20e3]
│1️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [31 fe0f 20e3]
│2️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [32 fe0f 20e3]
│3️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [33 fe0f 20e3]
│4️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [34 fe0f 20e3]
│5️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [35 fe0f 20e3]
│6️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [36 fe0f 20e3]
│7️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [37 fe0f 20e3]
│8️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [38 fe0f 20e3]
│9️⃣ │ │ Library: 2 Terminal: 1 Result: ✗ │ │ Padding: 1 Variant:  true │ Codepoints: [39 fe0f 20e3]
│🈂│ │ Library: 1 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [1f202]
│🈷│ │ Library: 1 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [1f237]
│㊗│ │ Library: 1 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [3297]
│㊙│ │ Library: 1 Terminal: 2 Result: ✗ │ │ Padding: 0 Variant: false │ Codepoints: [3299]
└──┘ └──────────────────────────────────┘ └───────────────────────────┘
Success: 4711, Total: 4733 (99.54%)
```

In this output `Library` means uniseg and `Terminal` means WezTerm. My main concerns are the first 5 being reported as a width of `0` when clearly there is some output.

However, I do realise that these may be like other selectors and by themselves act like ZWJ (0 width). Is this a case where it only applies with people emojis and changes their skin colour? Does this mean by themselves they are incomplete (and meaningless)?

WezTerm was also configured with the following option:
```ini
config.unicode_version = 14
```

Adding @wez to this because either way, there are some minor Unicode differences between uniseg and WezTerm so there is a bug somewhere. 😄 

@jquast I used your method from ucs-detect to query the cursor position before and after sending the emoji.

**Comment by mikelorant** [comment]
Closing this issue as this just shows subtle but inconsequential differences. Not important enough to warrant any attention.

**Comment by rivo** [comment]
I'm planning to look at this but haven't had a chance yet. So I might reply at some point despite this being closed.

**Comment by mikelorant** [comment]
@rivo My apologies then. I thought it was interesting as I was hoping we might have both a library and terminal that had consensus on every codepoint. WezTerm and Uniseg were very close and the slight differences might be useful for identifying some confusion with edge cases.
