### ISSUE TITLE
Codegen for Unicode Test cases?

### ISSUE THREAD

**Issue by dchapes** [rivo/uniseg#9]
After reading https://github.com/rivo/uniseg/issues/6#issuecomment-633389924, I have a question about how those parts of the case where added and how they are maintained.

I.e. the lines starting at:

https://github.com/rivo/uniseg/blob/f699dde9c340bcc39b69a4c67369832af73ec72e/grapheme_test.go#L43-L47

Where these entered by hand or generated by code that you have but that isn't committed?

If the later, would you please consider committing it such that those tests can be re-generated, updated, etc via [`go generate`](https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source). If you have such code but it's not of a suitable quality to commit (e.g. you hacked something disposable together that did the job "good enough" for the first commit) then, if you'd like, I could take that code and clean it up for you.

If the former, would you be open to a PR that given a URL would code generate the relevant test cases? I imaging something like a `grapheme_test_gen.go` file with a `// +build generate` tag that generates just the sub-slice of unicode.org tests to a new file, e.g. `grapheme_gen_test.go`, that is then just referenced from the existing hand written `grapheme_test.go` file, which would have an appropriate `//go:generate go run grapheme_test_gen.go https://www.unicode.org/Public/13.0.0/ucd/auxiliary/GraphemeBreakTest.txt` line that could be easily be changed.

Further, are there other parts of the code that could possibly benefit from code generation from other pages at `https://www.unicode.org/Public/13.0.0/ucd/auxiliary/` or elsewhere? Possibly the rules in `grTransitions` or the property `codePoints` slice? Would you also be open to PRs for such changes? The goal wouldn't be to harm code readability in any way but instead to allow easier and far less error-prone updating as/when Unicode changes/evolves. Examples of doing such things can be found in places such as [`golang.org/x/text/unicode`](https://golang.org/x/text/unicode).

Thank you.

**Comment by rivo** [comment]
> Where these entered by hand or generated by code that you have but that isn't committed?

By hand via search & replace.

> Further, are there other parts of the code that could possibly benefit from code generation from other pages at https://www.unicode.org/Public/13.0.0/ucd/auxiliary/ or elsewhere? Possibly the rules in `grTransitions` or the property `codePoints` slice?

I created the transitions rules manually based on this: https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules. I'm not sure if it's possible to automatically generate correct code from the information provided in the Unicode specification. Haven't looked into that yet. (And I probably only will when the need for it arises.)

> I had some free time so for kicks I went ahead and did a PR for the first part of this.

Thanks. I will provide some feedback to your PR.
